set(WARNINGS "/W4 /WX /w14445 /w14640 /w14242 /w14263 /w14265")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${WARNINGS} /Ios\\win32 /nologo /MD")

add_definitions("/D_CRT_SECURE_NO_WARNINGS /DSTDC_WANT_LIB_EXT2__=1")

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /Od /Zi /GS")
else()
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /O2 /GL /GS /D_FORTIFY_SOURCE=2")
    set(CMAKE_C_LINK_FLAGS "${CMAKE_C_LINK_FLAGS} /LTCG /INCREMENTAL:NO /OPT:REF /OPT:ICF")
endif()