name: Linux (with GCC)

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/mattkretz/cplusplus-ci/gcc16

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: apt-get install -y openssl
      - name: Configure CMake
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
      - name: Build executable
        working-directory: ./build
        run: make neblina
      - name: Build and run tests
        working-directory: ./build
        run: make neblina-tests && ./neblina-tests
