name: Windows (with MSVC)

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64
      - name: Run tests
        run: mkdir build && cd build && cmake .. && msbuild neblina.sln /t:neblina-tests && cd Debug && dir && .\neblina-tests.exe && cd ..
      - name: Create executable
        run: cd build && msbuild neblina.sln /t:neblina /p:Configuration=Release && cd Release && 7z a neblina-win64.zip neblina.exe
      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'push' }}
        with:
          files: Release\neblina-win64.zip
